#%RAML 0.8
title: "LocalAPI Example RAML"
version: "v1"
baseUri: "https://example.com"
protocols: [HTTPS]
mediaType: "application/json"

resourceTypes:
  - collection:
      description: Collection of available <<resourcePathName>>.
      get?:
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"
  - collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get?:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
        responses:
          200:
            description: Success!
            body:
              application/json:
                example: "example"
                schema: "schema"
/users:
  type: collection
  displayName: Users
  post:
    body:
      application/json:
        schema: !include schemas/user_post.json
        example: !include examples/user_post.json
    responses:
      201:
        body:
          application/json:
            schema: !include schemas/user.json
            example: !include examples/user.json
  get:
    responses:
      200:
        headers:
            Access-Control-Allow-Origin:
              example: "*"
            Access-Control-Allow-Methods:
              example: "GET, POST"
            Access-Control-Allow-Headers:
              example: "Content-Type"
        body:
          application/json:
            schema: !include schemas/users.json
            example: !include examples/users.json
  /{userId}:
    type: collection-item
    uriParameters:
      userId:
        displayName: User ID
        type: string
        required: true
    put:
      body:
        application/json:
          schema: !include schemas/user_put.json
          example: !include examples/user.json
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/user.json
              example: !include examples/user.json
    delete:
      responses:
        200:
          body:
            application/json:
              example: "{}"
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/user.json
              example: !include examples/user.json